[package]
name = "auto-clicker"
version = "0.0.1"
authors = ["SnowViktor"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/SnowViktor/auto-clicker"
license = "MIT"

[profile.release]
opt-level = "s"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser"] } 
